services:
  react:
    build:
      context: .
      dockerfile: ./docker/client-app/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/client-app/conf.d:/etc/nginx/conf.d:ro
      - ./docker/client-app/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
    restart: always
  webapi:
    build:
      context: .
      dockerfile: ./docker/web-api/Dockerfile
    depends_on:
      - database
    environment:
      ConnectionStrings__DbContext: Host=database;Database=${DATABASE};Username=${DB_USERNAME};Password=${DB_PASSWORD}
    networks:
      - frontend
      - backend
    restart: always
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
