version: '3.7'
services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - frontend
    restart: always
  app:
    build: ./src/
    depends_on:
      - database
    networks:
      - frontend
      - backend
    restart: always
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge