version: '3.7'
services:
  react:
    build: ./src/ClientApp/
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
  webapi:
    build: ./src/
    networks:
      - frontend
    ports:
      - 5000:5000
    restart: always
networks:
  frontend:
    driver: bridge
