version: '3.7'
services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - frontend
    restart: always
  app:
    build: ./src/
    networks:
      - frontend
networks:
  frontend:
    driver: bridge