/* tslint:disable */
/* eslint-disable */
/**
 * Sample API
 * This is just sample
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WeatherForecastDto
 */
export interface WeatherForecastDto {
    /**
     * 
     * @type {Date}
     * @memberof WeatherForecastDto
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof WeatherForecastDto
     */
    temperatureC: number;
    /**
     * 
     * @type {number}
     * @memberof WeatherForecastDto
     */
    readonly temperatureF: number;
    /**
     * 
     * @type {string}
     * @memberof WeatherForecastDto
     */
    summary: string;
}

export function WeatherForecastDtoFromJSON(json: any): WeatherForecastDto {
    return WeatherForecastDtoFromJSONTyped(json, false);
}

export function WeatherForecastDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeatherForecastDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'temperatureC': json['temperatureC'],
        'temperatureF': json['temperatureF'],
        'summary': json['summary'],
    };
}

export function WeatherForecastDtoToJSON(value?: WeatherForecastDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': (value.date.toISOString()),
        'temperatureC': value.temperatureC,
        'summary': value.summary,
    };
}

