/* tslint:disable */
/* eslint-disable */
/**
 * Sample API
 * This is just sample
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WeatherForecast
 */
export interface WeatherForecast {
    /**
     * 
     * @type {Date}
     * @memberof WeatherForecast
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof WeatherForecast
     */
    temperatureC: number;
    /**
     * 
     * @type {number}
     * @memberof WeatherForecast
     */
    readonly temperatureF: number;
    /**
     * 
     * @type {string}
     * @memberof WeatherForecast
     */
    summary: string;
}

export function WeatherForecastFromJSON(json: any): WeatherForecast {
    return WeatherForecastFromJSONTyped(json, false);
}

export function WeatherForecastFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeatherForecast {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'temperatureC': json['temperature_c'],
        'temperatureF': json['temperature_f'],
        'summary': json['summary'],
    };
}

export function WeatherForecastToJSON(value?: WeatherForecast | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': (value.date.toISOString()),
        'temperature_c': value.temperatureC,
        'summary': value.summary,
    };
}

