env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - plugin:prettier/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
rules:
  react/react-in-jsx-scope: off
  "@typescript-eslint/triple-slash-reference": off
ignorePatterns:
  - "vite.config.ts"
settings:
  react:
    version: "detect"