/* tslint:disable */
/* eslint-disable */
/**
 * Sample API
 * This is just sample
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    WeatherForecast,
    WeatherForecastFromJSON,
    WeatherForecastToJSON,
} from '../models';

/**
 * WeatherForecastApi - interface
 * 
 * @export
 * @interface WeatherForecastApiInterface
 */
export interface WeatherForecastApiInterface {
    /**
     * 
     * @summary Gets weather forecast information
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherForecastApiInterface
     */
    getWeatherForecastsRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<WeatherForecast>>>;

    /**
     * Gets weather forecast information
     */
    getWeatherForecasts(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<WeatherForecast>>;

}

/**
 * 
 */
export class WeatherForecastApi extends runtime.BaseAPI implements WeatherForecastApiInterface {

    /**
     * Gets weather forecast information
     */
    async getWeatherForecastsRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<WeatherForecast>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/weather-forecasts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WeatherForecastFromJSON));
    }

    /**
     * Gets weather forecast information
     */
    async getWeatherForecasts(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<WeatherForecast>> {
        const response = await this.getWeatherForecastsRaw(initOverrides);
        return await response.value();
    }

}
