name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/src
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './frontend/src/package-lock.json'
    - name: Restore node modules cache
      uses: actions/cache@v3
      id: node-module-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('./frontend/src/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('./frontend/src/packages.lock.json') }}
    - name: Restore dependencies
      run: npm ci
    - name: Check dependency module security
      run: npm audit --audit-level=high --omit=dev
    - name: Build
      run: npm run build
    - name: Check source format
      run: npm run lint
    - name: Test
      run: npm test
