name: Node.js CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Frontend
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './src/Frontend/package-lock.json'
    - name: Restore dependencies
      run: npm ci
    - name: Check dependency module security
      run: npm audit --audit-level=high --omit=dev
    - name: Build
      run: npm run build
    - name: Check source format
      run: npm run lint
    - name: Test
      run: npm test
